prepare_environment:
  stage: prepare
  script:
    - R -e "dir.create(`~/.Rlib')"
    - (export R_LIBS_USER='~/.Rlib'; export R_LIBS_SITE='~/.Rlib'; R --vanilla -e "install.packages('devtools', lib = '~/.Rlib`, repos = 'http://r-cran.manifesto-project.wzb.eu'); library(devtools); install_deps(dependencies = c('Depends', 'Imports','Suggests'), lib = '~/.Rlib`, repos = 'http://r-cran.manifesto-project.wzb.eu');")

compile_vignette:
  stage: vignette
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - mkdir inst/doc
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sR.rsp', '\\\\1 knitr', .) } %>% writeLines('DESCRIPTION')"
    - cat DESCRIPTION
    - R --vanilla -e "library(devtools); with_libpaths('~/.Rlib', build_vignettes());"
    - cp inst/doc/manifestoRworkflow.pdf vignettes/
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sknitr', '\\\\1 R.rsp', .) } %>% writeLines('DESCRIPTION')"
  artifacts:
    paths:
      - vignettes/manifestoRworkflow.pdf
      - inst/doc/manifestoRworkflow.pdf
      
test_manifestoR:
  stage: test
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - R --vanilla -e "library(devtools); library(withr); withr::with_libpaths('~/.Rlib', { document(); library(testthat); test(reporter = 'stop') })"

pack_manifestoR:
  stage: pack
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - mkdir inst/doc
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sR.rsp', '\\\\1 knitr', .) } %>% writeLines('DESCRIPTION')"
    - cat DESCRIPTION
    - R --vanilla -e "library(devtools); library(withr); withr::with_libpaths('~/.Rlib', build_vignettes());"
    - cp inst/doc/manifestoRworkflow.pdf vignettes/
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sknitr', '\\\\1 R.rsp', .) } %>% writeLines('DESCRIPTION')"
    - R --vanilla -e "library(devtools); library(withr); withr::with_libpaths('~/.Rlib', { document(); file.copy(build(path = './'), 'manifestoR.tar.gz') })"
    - (export R_LIBS_SITE='~/.Rlib';  R -e ".libPaths()"; R CMD check --as-cran manifestoR.tar.gz)
    - cat manifestoR.Rcheck/00install.out
  artifacts:
    paths:
    - manifestoR.tar.gz
    - check_results.txt

stages:
  - prepare
  - test
  - vignette
  - pack
