prepare_environment:
  stage: prepare
  script:
    - R -e "dir.create('~/.Rlib'); library(devtools); with_libpaths('~/.Rlib/', {
        install_deps(dependencies = c('Depends', 'Imports','Suggests'), repos = 'http://r-cran.manifesto-project.wzb.eu');
        document();})"
        
compile_vignette:
  stage: vignette
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - mkdir inst/doc
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sR.rsp', \\\\1 knitr', .) } %>% writeLines('DESCRIPTION')"
    - R -e "library(devtools); with_libpaths('~/.Rlib', build_vignettes());"
    - cp inst/doc/manifestoRworkflow.pdf vignettes/
    - R -e "library(magrittr); 'DESCRIPTION' %>% readLines() %>% { gsub('(VignetteBuilder.)\\\\sknitr', '\\\\1 R.rsp', .) } %>% writeLines('DESCRIPTION')"
  artifacts:
    paths:
      - vignettes/manifestoRworkflow.pdf

pack_manifestoR:
  stage: build
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - mkdir inst/doc
    - R CMD build ./
    - mv manifestoR*.tar.gz manifestoR.tar.gz
    - R CMD check --as-cran manifestoR.tar.gz > check_results.txt
    - cat check_results.txt
  artifacts:
    paths:
    - manifestoR.tar.gz
    - check_results.txt

test_manifestoR:
  stage: build
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - R -e "library(devtools); document()"
    - make test

stages:
  - prepare
  - vignette
  - build
