prepare_environment:
  stage: prepare
  script:
    - R -e "dir.create('~/.Rlib'); library(devtools); with_libpaths('~/.Rlib/', {
        install_deps(dependencies = c('Depends', 'Imports','Suggests'), repos = 'http://r-cran.manifesto-project.wzb.eu');
        document();})"

pack_manifestoR:
  stage: build
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - mkdir inst/doc
    - make Rmdvignette
    - R CMD build ./
    - mv manifestoR*.tar.gz manifestoR.tar.gz
    - R CMD check --as-cran manifestoR.tar.gz > check_results.txt
    - cat check_results.txt
  artifacts:
    paths:
    - manifestoR.tar.gz
    - check_results.txt
    - vignettes/manifestoRworkflow.pdf

test_manifestoR:
  stage: build
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - R -e "library(devtools); document()"
    - make test

stages:
  - prepare
  - build

  
