pack_manifestoR:
  stage: build
  script:
    - R -e "library(devtools); document()"
    - R CMD build ./
    - mv manifestoR*.tar.gz manifestoR.tar.gz
    - R CMD check --as-cran manifestoR.tar.gz > check_results.txt
  artifacts:
    paths:
    - manifestoR.tar.gz
    - check_results.txt

stages:
  - build

  