pack_manifestoR:
  stage: build
  script:
    - echo $MANIFESTOAPIKEY > tests/manifesto_apikey.txt
    - R -e "library(devtools); document()"
    - make Rmdvignette
    - R CMD build ./
    - mv manifestoR*.tar.gz manifestoR.tar.gz
    - R CMD check --as-cran manifestoR.tar.gz > check_results.txt
  artifacts:
    paths:
    - manifestoR.tar.gz
    - check_results.txt
    - vignettes/manifestoRworkflow.pdf

stages:
  - build

  